name: Binary release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-binary:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
 
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install -g npm@latest
          npm audit fix
          npm uninstall node-pre-gyp --save
          npm install @mapbox/node-pre-gyp --save
          npm i pkg
          npx pkg .

      - uses: papeloto/action-zip@v1
        with:
          files: ss-bin/
          dest: ss-bin.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./ss-bin.zip
          asset_name: slideshow-bin.${{ steps.create_release.tag_name }}.zip
          asset_content_type: application/zip


